<a href="https://colab.research.google.com/github/JodhiKrisantus/Machine-Learning/blob/main/KNN_Titanic_MachineLearning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import itertools
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn import preprocessing
from sklearn.preprocessing import StandardScaler

In [ ]:
df = pd.read_csv("https://raw.githubusercontent.com/rasyidev/well-known-datasets/main/titanic.csv")
df.head()

PassengerId  Pclass                                               Name  \
0            1       3                            Braund, Mr. Owen Harris   
1            2       1  Cumings, Mrs. John Bradley (Florence Briggs Th...   
2            3       3                             Heikkinen, Miss. Laina   
3            4       1       Futrelle, Mrs. Jacques Heath (Lily May Peel)   
4            5       3                           Allen, Mr. William Henry   

      Sex   Age  SibSp  Parch            Ticket Cabin Embarked  Survived  
0    male  22.0      1      0         A/5 21171   NaN        S         0  
1  female  38.0      1      0          PC 17599   C85        C         1  
2  female  26.0      0      0  STON/O2. 3101282   NaN        S         1  
3  female  35.0      1      0            113803  C123        S         1  
4    male  35.0      0      0            373450   NaN        S         0

In [ ]:
df.drop(columns=["Name","Ticket","Cabin"],inplace=True)

In [ ]:
df

PassengerId  Pclass     Sex   Age  SibSp  Parch Embarked  Survived
0              1       3    male  22.0      1      0        S         0
1              2       1  female  38.0      1      0        C         1
2              3       3  female  26.0      0      0        S         1
3              4       1  female  35.0      1      0        S         1
4              5       3    male  35.0      0      0        S         0
..           ...     ...     ...   ...    ...    ...      ...       ...
886          887       2    male  27.0      0      0        S         0
887          888       1  female  19.0      0      0        S         1
888          889       3  female   NaN      1      2        S         0
889          890       1    male  26.0      0      0        C         1
890          891       3    male  32.0      0      0        Q         0

[891 rows x 8 columns]

In [ ]:
df.isnull().sum()

PassengerId      0
Pclass           0
Sex              0
Age            177
SibSp            0
Parch            0
Embarked         2
Survived         0
dtype: int64

In [ ]:
#df.fillna(df["Age"].mean(),inplace=True)
df['Age'].fillna(value=df['Age'].mean(), inplace=True)
df['Embarked'].fillna(value=df['Embarked'].mode()[0], inplace=True)

In [ ]:
df.isnull().sum()

PassengerId    0
Pclass         0
Sex            0
Age            0
SibSp          0
Parch          0
Embarked       0
Survived       0
dtype: int64

In [ ]:
df

PassengerId  Pclass     Sex        Age  SibSp  Parch Embarked  Survived
0              1       3    male  22.000000      1      0        S         0
1              2       1  female  38.000000      1      0        C         1
2              3       3  female  26.000000      0      0        S         1
3              4       1  female  35.000000      1      0        S         1
4              5       3    male  35.000000      0      0        S         0
..           ...     ...     ...        ...    ...    ...      ...       ...
886          887       2    male  27.000000      0      0        S         0
887          888       1  female  19.000000      0      0        S         1
888          889       3  female  29.699118      1      2        S         0
889          890       1    male  26.000000      0      0        C         1
890          891       3    male  32.000000      0      0        Q         0

[891 rows x 8 columns]

# ENDCODE KOLOM SEX MENJADI :
- Male = 1
- Female = 0

In [ ]:
from sklearn.preprocessing import LabelEncoder
sex_endcode = LabelEncoder()
sex_endcode.fit(df["Sex"])
sex_= sex_endcode.transform(df["Sex"])
sex_

array([1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1,
       0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0,
       0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1,
       0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1,
       0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0,
       1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1,
       0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1,
       1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1,
       0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0,
       1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1,
       0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0,

In [ ]:
embarked_col = df["Embarked"]
embarked_encode = LabelEncoder()
embarked_encode.fit(df["Embarked"])
embarked_= embarked_encode.transform(df["Embarked"])
embarked_

array([2, 0, 2, 2, 2, 1, 2, 2, 2, 0, 2, 2, 2, 2, 2, 2, 1, 2, 2, 0, 2, 2,
       1, 2, 2, 2, 0, 2, 1, 2, 0, 0, 1, 2, 0, 2, 0, 2, 2, 0, 2, 2, 0, 0,
       1, 2, 1, 1, 0, 2, 2, 2, 0, 2, 0, 2, 2, 0, 2, 2, 0, 2, 2, 2, 0, 0,
       2, 2, 2, 2, 2, 2, 2, 0, 2, 2, 2, 2, 2, 2, 2, 2, 1, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 0, 0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1,
       2, 0, 2, 2, 0, 2, 1, 2, 0, 2, 2, 2, 0, 2, 2, 0, 1, 2, 0, 2, 0, 2,
       2, 2, 2, 0, 2, 2, 2, 0, 0, 2, 2, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 0, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 2, 2, 0, 2,
       2, 0, 2, 2, 2, 0, 2, 2, 2, 2, 1, 2, 1, 2, 2, 2, 2, 2, 0, 0, 1, 2,
       1, 2, 2, 2, 2, 0, 2, 2, 2, 0, 1, 0, 2, 2, 2, 2, 1, 0, 2, 2, 0, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 1,
       2, 2, 0, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 0, 2, 0, 2, 1, 2, 2, 2,
       1, 2, 2, 2, 2, 2, 2, 2, 2, 0, 1, 2, 2, 2, 1, 2, 1, 2, 2, 2, 2, 0,
       2, 2, 2, 1, 2, 0, 0, 2, 2, 0, 0, 2, 2, 0, 1,

MEMASUKKAN HASIL ENDCODE KE DATAFRAME

In [ ]:
df = df.assign(Sex=sex_)

In [ ]:
df = df.assign(Embarked=embarked_)

In [ ]:
df

PassengerId  Pclass  Sex        Age  SibSp  Parch  Embarked  Survived
0              1       3    1  22.000000      1      0         2         0
1              2       1    0  38.000000      1      0         0         1
2              3       3    0  26.000000      0      0         2         1
3              4       1    0  35.000000      1      0         2         1
4              5       3    1  35.000000      0      0         2         0
..           ...     ...  ...        ...    ...    ...       ...       ...
886          887       2    1  27.000000      0      0         2         0
887          888       1    0  19.000000      0      0         2         1
888          889       3    0  29.699118      1      2         2         0
889          890       1    1  26.000000      0      0         0         1
890          891       3    1  32.000000      0      0         1         0

[891 rows x 8 columns]

Bagi X(Fitur) dan y(Target)

In [ ]:
X = df[["PassengerId",	"Pclass","Age",	"SibSp",	"Parch","Sex","Embarked"]].values
X[0:5]

array([[ 1.,  3., 22.,  1.,  0.,  1.,  2.],
       [ 2.,  1., 38.,  1.,  0.,  0.,  0.],
       [ 3.,  3., 26.,  0.,  0.,  0.,  2.],
       [ 4.,  1., 35.,  1.,  0.,  0.,  2.],
       [ 5.,  3., 35.,  0.,  0.,  1.,  2.]])

In [ ]:
y = df["Survived"].values
y[0:5]

array([0, 1, 1, 1, 0])

# Normalisasi Data

K-NN merupakan metode yang didasarkan pada tingkat kedekatan antar-atribut. Oleh karena itu, sangat disarankan untuk melakukan normalisasi data agar perhitungan jarak menjadi lebih valid.

Digunakan untuk Press Data Agar lebih kecil

In [ ]:
Standar_Scaler = StandardScaler()
X = Standar_Scaler.fit_transform(X)
X

array([[-1.73010796,  0.82737724, -0.5924806 , ..., -0.47367361,
         0.73769513,  0.58595414],
       [-1.72622007, -1.56610693,  0.63878901, ..., -0.47367361,
        -1.35557354, -1.9423032 ],
       [-1.72233219,  0.82737724, -0.2846632 , ..., -0.47367361,
        -1.35557354,  0.58595414],
       ...,
       [ 1.72233219,  0.82737724,  0.        , ...,  2.00893337,
        -1.35557354,  0.58595414],
       [ 1.72622007, -1.56610693, -0.2846632 , ..., -0.47367361,
         0.73769513, -1.9423032 ],
       [ 1.73010796,  0.82737724,  0.17706291, ..., -0.47367361,
         0.73769513, -0.67817453]])

Split menjadi X_train, X_test, y_train, y_test

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split( X, y, test_size=0.2, random_state=5)


TRAINING

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=6)
knn.fit(X_train,y_train)#TRAINING

KNeighborsClassifier(n_neighbors=6)

# PREDICT
Setelah data selesai di Training (Fitting), maka barulah kita bisa **Memprediksi nilai  y, dari data yang belum di training (X_test)**

In [ ]:
y_pred = knn.predict(X_test)

# ACCURACY

In [ ]:
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.83      0.94      0.88       111
           1       0.87      0.68      0.76        68

    accuracy                           0.84       179
   macro avg       0.85      0.81      0.82       179
weighted avg       0.84      0.84      0.83       179



In [ ]:
np.mean(y_pred == y_test)

0.8379888268156425

0.8379888268156425