<a href="https://colab.research.google.com/github/JodhiKrisantus/Machine-Learning/blob/main/Logistic_Regression_BankChurn.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
import sklearn

In [ ]:
df = pd.read_csv("https://raw.githubusercontent.com/rasyidev/well-known-datasets/main/bank_churn.csv")
df.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   RowNumber        10000 non-null  int64  
 1   CustomerId       10000 non-null  int64  
 2   Surname          10000 non-null  object 
 3   CreditScore      10000 non-null  int64  
 4   Geography        10000 non-null  object 
 5   Gender           10000 non-null  object 
 6   Age              10000 non-null  int64  
 7   Tenure           10000 non-null  int64  
 8   Balance          10000 non-null  float64
 9   NumOfProducts    10000 non-null  int64  
 10  HasCrCard        10000 non-null  int64  
 11  IsActiveMember   10000 non-null  int64  
 12  EstimatedSalary  10000 non-null  float64
 13  Exited           10000 non-null  int64  
dtypes: float64(2), int64(9), object(3)
memory usage: 1.1+ MB


In [ ]:
print("gender \t\t",df.Gender.nunique())
print("geography \t",df.Geography.nunique())
print("Tenure \t\t",df.Tenure.nunique())
print("NumOf Product \t",df.NumOfProducts.nunique())
print("Has Credit \t",df.HasCrCard.nunique())
print("Member aktif \t",df.IsActiveMember.nunique())
print("RowNumber \t\t",df.RowNumber.nunique())

gender 		 2
geography 	 3
Tenure 		 11
NumOf Product 	 4
Has Credit 	 2
Member aktif 	 2
RowNumber 		 10000


In [ ]:
df.isnull().sum()

RowNumber          0
CustomerId         0
Surname            0
CreditScore        0
Geography          0
Gender             0
Age                0
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
Exited             0
dtype: int64

In [ ]:
df.duplicated().sum()

0

# **ENDCODING**

In [ ]:
from sklearn.preprocessing import LabelEncoder
endcode = LabelEncoder()

In [ ]:
#ENDCODE GENDER
gender = endcode.fit(df["Gender"])
gender = endcode.transform(df["Gender"])

#ENDCODE GEOGRAPHY
geo = endcode.fit(df["Geography"])
geo = endcode.transform(df["Geography"])

MASUKKAN DATA ENDCODE KE DATAFRAME

In [ ]:
df = df.assign(Gender = gender)
df = df.assign(Geography = geo)
df.head()

RowNumber  CustomerId   Surname  CreditScore  Geography  Gender  Age  \
0          1    15634602  Hargrave          619          0       0   42   
1          2    15647311      Hill          608          2       0   41   
2          3    15619304      Onio          502          0       0   42   
3          4    15701354      Boni          699          0       0   39   
4          5    15737888  Mitchell          850          2       0   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

## DROP KOLOM YANG TIDAK DIBUTUHKAN

In [ ]:
df.drop(columns=["RowNumber","Surname","CustomerId"], inplace = True)

In [ ]:
df.head()

CreditScore  Geography  Gender  Age  Tenure    Balance  NumOfProducts  \
0          619          0       0   42       2       0.00              1   
1          608          2       0   41       1   83807.86              1   
2          502          0       0   42       8  159660.80              3   
3          699          0       0   39       1       0.00              2   
4          850          2       0   43       2  125510.82              1   

   HasCrCard  IsActiveMember  EstimatedSalary  Exited  
0          1               1        101348.88       1  
1          0               1        112542.58       0  
2          1               0        113931.57       1  
3          0               0         93826.63       0  
4          1               1         79084.10       0

# MEMBAGI FITUR X dan y

In [ ]:
X = df.iloc[:,:-1]
y = df["Exited"]

## PRESS DATA / NORMALISASI DATA (SCALLING)

In [ ]:
from sklearn.preprocessing import StandardScaler
Standard_Scaller = StandardScaler()
X = Standard_Scaller.fit_transform(X)
X[0:3]

array([[-0.32622142, -0.90188624, -1.09598752,  0.29351742, -1.04175968,
        -1.22584767, -0.91158349,  0.64609167,  0.97024255,  0.02188649],
       [-0.44003595,  1.51506738, -1.09598752,  0.19816383, -1.38753759,
         0.11735002, -0.91158349, -1.54776799,  0.97024255,  0.21653375],
       [-1.53679418, -0.90188624, -1.09598752,  0.29351742,  1.03290776,
         1.33305335,  2.52705662,  0.64609167, -1.03067011,  0.2406869 ]])

SPLIT DATA MENJADI X_train, X_test, y_train, y_test

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size = 0.3)

## TRAINING

In [ ]:
from sklearn.linear_model import LogisticRegression
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import PolynomialFeatures
Logistik_regression = LogisticRegression(max_iter = 100,random_state=4)
# pipeline = Pipeline(steps = [('add_poly_features', PolynomialFeatures()),
#                              ('logistic_regression',LogisticRegression)] )

In [ ]:
y_train.ndim

1

In [ ]:
Logistik_regression.fit(X_train, y_train)

LogisticRegression(random_state=4)

## PREDIKSI

In [ ]:
y_pred = Logistik_regression.predict(X_test)
y_pred[:20]

array([0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

## AKURASI

In [ ]:
np.mean(y_pred == y_test)

0.816

In [ ]:
from sklearn import metrics
metrics.accuracy_score(y_pred, y_test)

0.816

In [ ]:
from sklearn.metrics import classification_report
print(classification_report(y_pred, y_test))

              precision    recall  f1-score   support

           0       0.97      0.83      0.89      2819
           1       0.18      0.59      0.28       181

    accuracy                           0.82      3000
   macro avg       0.58      0.71      0.59      3000
weighted avg       0.92      0.82      0.86      3000



# CARI True Positif, True Negatif, False Positif, False Negatif

In [ ]:
from sklearn.metrics import confusion_matrix
matrix = confusion_matrix(y_test, y_pred)
matrix

array([[2341,   74],
       [ 478,  107]])

In [ ]:
tn, fp, fn, tp = matrix.ravel()
print("TN ", tn )
print("FP ", fp)
print("FN ", fn)
print("TP ", tp)

TN  2341
FP  74
FN  478
TP  107


# COBA PREDIKSI SATU DATA

In [ ]:
df

CreditScore  Geography  Gender  Age  Tenure    Balance  NumOfProducts  \
0             619          0       0   42       2       0.00              1   
1             608          2       0   41       1   83807.86              1   
2             502          0       0   42       8  159660.80              3   
3             699          0       0   39       1       0.00              2   
4             850          2       0   43       2  125510.82              1   
...           ...        ...     ...  ...     ...        ...            ...   
9995          771          0       1   39       5       0.00              2   
9996          516          0       1   35      10   57369.61              1   
9997          709          0       0   36       7       0.00              1   
9998          772          1       1   42       3   75075.31              2   
9999          792          0       0   28       4  130142.79              1   

      HasCrCard  IsActiveMember  EstimatedSalary  Exited  
0             1               1        101348.88       1  
1             0               1        112542.58       0  
2             1               0        113931.57       1  
3             0               0         93826.63       0  
4             1               1         79084.10       0  
...         ...             ...              ...     ...  
9995          1               0         96270.64       0  
9996          1               1        101699.77       0  
9997          0               1         42085.58       1  
9998          1               0         92888.52       1  
9999          1               0         38190.78       0  

[10000 rows x 11 columns]

In [ ]:
X_test[3]
y_pred = Logistik_regression.predict([[619,	0,	0,	42,	2,	0.00,	1,	1,	1,	101348.88	]])
y_pred